# Project Information
site_name: OI-WiKi
site_description: OI-WiKi
site_author: OIerKimi Team
site_url: https://OIerKimi.github.io/OI-Wiki
strict: false

# Repository
repo_name: 'OIerKimi/OI-Wiki'
repo_url: 'https://github.com/OIerKimi/OI-Wiki'
edit_uri: 'https://github.com/OIerKimi/OI-Wiki/edit/main/docs/'

# Copyright
copyright: 'Copyright &copy; 2024 My Team'

# Contents
nav:
  - 首页: index.md
  - 图论: GraphTheory.md

# Theme
theme:
  name: material
  language: 'zh'
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: blue
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: pink
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# Markdown Extensions
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - tables
  - footnotes
  - markdown_katex  # 添加 KaTeX 支持

# Plugins
plugins:
  - mkdocs-pdf-export-plugin:
      pdf_file_name: OI_Wiki_Documentation.pdf
      include_navigation: true
      include_cover: true
  - mkdocs-markdownextradata-plugin  # 添加此插件以支持 LaTeX 语法

# Extra
extra:
  comments:
    provider: giscus
    repo: OIerKimi/OI-Wiki
    repo_id: YOUR_REPO_ID  # 替换为你的 GitHub 仓库 ID
    category: Discussions
    category_id: YOUR_CATEGORY_ID  # 替换为讨论类别 ID
