name: Build and Deploy MkDocs

on:
  push:
    branches:
      - main  # 在主分支推送时执行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install MkDocs
        run: pip install mkdocs

      - name: Install MkDocs Material
        run: pip install mkdocs-material

      - name: Install PDF Export Plugin
        run: pip install mkdocs-pdf-export-plugin

      - name: Install KaTeX
        run: pip install markdown-katex

      - name: Build MkDocs
        run: mkdocs build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site