name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main  # 根据您的默认分支名称调整

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 确保检出所有历史记录

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # 指定所需的 Python 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material

      - name: Build MkDocs site
        run: mkdocs build --clean

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_dir: ./site
          # 可选配置：
          # publish_branch: gh-pages  # 目标分支，默认为 gh-pages
          # force_orphan: true  # 如果需要覆盖历史记录
